### PR TITLE
Use st_mtime instead of st_ctime

### PR DESCRIPTION
**Pull request by kb323**
stat.st_ctime returns the creation time of the file on Windows (which doesn't change with new messages), and the modification time of the file *metadata* on Unix/Mac. stat.st_mtime should return the modification time of the file contents (i.e. time of last write to the file) across all platforms.

### CODE REVIEW

**Comment by ftc2** [comment]
i'm not opposed to the change, but firstly i'm curious if there's a situation where that matters. can you explain where it might?

the scenario i have in mind is where a client closes a file and starts writing to a new one. seems like creation time is fine there?

**Comment by ftc2** [comment]
well, regardless, i can't think of a case where using `st_mtime` would actually be worse than `st_ctime`.

**Comment by ftc2** [comment]
thanks for the pr

**Comment by kb323** [comment]
Basically with `ctime` the script is broken on Windows (won't detect new messages), and with Unix/Mac it is still fine. On Unix/Mac `ctime` and `mtime` on Unix/Mac basically store the same value.

On Windows, "Creation time" means the time that the log file first started existing, which is different from "Modification time" when the file was last changed. 

For example, when I run the script I have `chatA.log` created on April 30, 12 PM and `chatB.log` created on April 30, 1 PM. These are the times when I first opened the chat windows `chatA` and `chatB`.

However, the most recent message in `chatA.log` was April 30, 5 PM and in `chatB.log` was April 30, 1:01 PM. These correspond to the **modification times** of the files.

When using `stat.ctime` on Windows, it will **always** see `chatB` as the newest log file, i.e. the file with the max ctime. We know that `chatA` had a more recent message (5 PM!) and was modified more recently, even though it was created earlier. By checking max `ctime` on Windows, the script will only and always parse `chatB` or otherwise some entirely new `chatC` which is created more recently. It will never look for messages in `chatA`.

**Comment by ftc2** [comment]
thanks for clarifying.

you're using it in a way that i didn't plan for. my envisioned use case was a log dir containing logs only for the relevant channel, so the most recently created file was always the only relevant one anyways.

**Comment by kb323** [comment]
ah, got it! yeah, I might have messed up here. Realized that when wanting to monitor multiple channels in a mixed log dir, the best solution is to spawn log_parse threads for each of the log files and have them all run concurrently, regardless of which one is latest...

**Comment by kb323** [comment]
Thanks for this in any case! Great script!

**Comment by ftc2** [comment]
well there are two issues.

first of all, when it switches to a new log file, the script misses that new line the first time if the file ends with a blank newline. it correctly grabs subsequent appends though. i'm fixing that rn.

second issue is in your mixed log dir situation. if multiple files are being frequently updated, lines can be missed if `log_scan()` doesn't switch to the new log fast enough (rn it scans for newer file every 1s). making a thread for each log file present (and adding a new thread as new files appear) could be better i guess. idk if you feel like taking a crack at that.

**Comment by ftc2** [comment]
moving the conversation over to an issue: https://github.com/ftc2/interview-notify/issues/4

**Pull request merged**
